// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// find_edges
IntegerMatrix find_edges(IntegerMatrix adj);
RcppExport SEXP minHomVoting_find_edges(SEXP adjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type adj(adjSEXP);
    rcpp_result_gen = Rcpp::wrap(find_edges(adj));
    return rcpp_result_gen;
END_RCPP
}
// adj_to_inc
IntegerMatrix adj_to_inc(IntegerMatrix adj);
RcppExport SEXP minHomVoting_adj_to_inc(SEXP adjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type adj(adjSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_to_inc(adj));
    return rcpp_result_gen;
END_RCPP
}
