# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title find edges
#' @description takes an adjacency matrix and generates a list of edges
#' @return a list with edges
#' @export
find_edges <- function(adj) {
    .Call('minHomVoting_find_edges', PACKAGE = 'minHomVoting', adj)
}

#' @title incidence matrix from adjacency matrix in reduced form
#' @description takes an adjacency matrix and generates the incidencematrix
#' @param adj an adjacency matrix
#' @details the incidence matrix \code{E} has entry \code{e_{ij}} equal to
#' \itemize{
#'     \code{1} if an edge starts in node \code{i} and finishes in \code{j}
#'     \code{-1} if an edge ends in node \code{i} and finishes in \code{j}
#'     \code{0} if nodes \code{i} and \code{j} are not connected
#' }
#' @return an incidence matrix
#' @export
adj_to_inc <- function(adj) {
    .Call('minHomVoting_adj_to_inc', PACKAGE = 'minHomVoting', adj)
}

