# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title incidence matrix from adjacency matrix in full form
#' @description takes an adjacency matrix and generates the incidencematrix
#' @param adj an adjacency matrix
#' @return an incidence matrix
#' @export
adj_to_inc <- function(adj) {
    .Call('minHomVoting_adj_to_inc', PACKAGE = 'minHomVoting', adj)
}

#' @title incidence matrix from adjacency matrix in reduced form
#' @description takes an adjacency matrix and generates the incidencematrix
#' @param adj an adjacency matrix
#' @return an incidence matrix
#' @export
adj_to_inc_reduced <- function(adj) {
    .Call('minHomVoting_adj_to_inc_reduced', PACKAGE = 'minHomVoting', adj)
}

